version: '3.4'

services:
  app-client:
    container_name: lista-dei-vini-client_1
    build:
      context: lista-dei-vini-client
      dockerfile: Dockerfile-buster #Dockerfile
    environment: 
      - ADB_IP=192.168.1.77
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.1.77
    ports: 
      - 19000:19000
      - 19001:19001
      - 19006:19006
    volumes: 
      - ${PWD}/:/app/
    depends_on: 
      - app-server
    networks: 
      - frontend

  app-server:
    container_name: lista-dei-vini-server_1
    build:
      context: lista-dei-vini-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks: 
      - backend
      - frontend
      
  database:
    image: postgres  # TODO: tag
    container_name: lista_dei_vini_database_1
    # restart: always
    env_file: configuration.env
    ports:
      - "5432:5432"
    volumes: 
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  frontend:
  backend:

volumes:
  db-data: