version: '3.4'

services:
  postgres:
    image: postgres  # TODO: tag
    # restart: always
    env_file: configuration.env
    ports:
      - 5432:5432

#networks:
#  frontend:
#  backend:

#volumes:
#  db-data: